export {
  addWakeWordListener,
  dispose,
  getStatus,
  initialize,
  startDetection,
  stopDetection,
  voiceActivator,
} from './public/voice-activator';
export { wakeWordStates } from './public/types';
export type {
  VoiceActivatorApi,
  WakeWordEngineAssetKeys,
  WakeWordEngineCapabilities,
  WakeWordEngineConfiguration,
  WakeWordEngineId,
  WakeWordEngineMetadata,
  WakeWordEngineMetadataValue,
  WakeWordEngineSelection,
  VoiceActivatorEventMap,
  WakeWordAudioRouteChangedEvent,
  WakeWordDetectedEvent,
  WakeWordError,
  WakeWordErrorCategory,
  WakeWordEventListener,
  WakeWordEventMap,
  WakeWordEventName,
  WakeWordInitializationOptions,
  WakeWordInterruptionEvent,
  WakeWordState,
  WakeWordStateChangedEvent,
  WakeWordStatus,
  WakeWordSubscription,
} from './public/types';
