name: Release Readiness

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-release-surface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Verify release readiness
        run: yarn verify:release-readiness

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Build example for Android
        env:
          JAVA_OPTS: "-XX:MaxHeapSize=6g"
        run: |
          yarn workspace react-native-voice-activator-example build:android

  build-ios:
    runs-on: macos-latest

    env:
      XCODE_VERSION: 16.3
      RCT_USE_RN_DEP: 1
      RCT_USE_PREBUILT_RNCORE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Use appropriate Xcode version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: example

      - name: Install cocoapods
        run: |
          cd example
          bundle exec pod repo update --verbose
          bundle exec pod install --project-directory=ios

      - name: Build example for iOS
        run: |
          yarn workspace react-native-voice-activator-example build:ios
